BATTLEPASS_CONFIG = {
    premiumCost = 5000,
    levelRewards = {
        [1] = { type = 'cash', amount = 250 },
        [2] = { type = 'cash', amount = 300 },
        [3] = { type = 'item', item = 'bandage', amount = 5 },
        [4] = { type = 'cash', amount = 350 },
        [5] = { type = 'weapon', weapon = 'pistol' },
        [6] = { type = 'cash', amount = 400 },
        [7] = { type = 'item', item = 'ammo-9', amount = 30 },
        [8] = { type = 'cash', amount = 450 },
        [9] = { type = 'item', item = 'lockpick', amount = 3 },
        [10] = { type = 'weapon', weapon = 'combatpistol' },
        [11] = { type = 'cash', amount = 500 },
        [12] = { type = 'item', item = 'bandage', amount = 10 },
        [13] = { type = 'cash', amount = 550 },
        [14] = { type = 'item', item = 'ammo-9', amount = 60 },
        [15] = { type = 'weapon', weapon = 'assaultrifle' },
        [16] = { type = 'cash', amount = 600 },
        [17] = { type = 'item', item = 'medikit', amount = 2 },
        [18] = { type = 'cash', amount = 650 },
        [19] = { type = 'item', item = 'ammo-rifle', amount = 45 },
        [20] = { type = 'weapon', weapon = 'carbinerifle' },
        [21] = { type = 'cash', amount = 750 },
        [22] = { type = 'item', item = 'bandage', amount = 15 },
        [23] = { type = 'cash', amount = 800 },
        [24] = { type = 'item', item = 'ammo-rifle', amount = 90 },
        [25] = { type = 'weapon', weapon = 'sniperrifle' },
        [26] = { type = 'cash', amount = 900 },
        [27] = { type = 'item', item = 'medikit', amount = 4 },
        [28] = { type = 'cash', amount = 1000 },
        [29] = { type = 'item', item = 'ammo-rifle', amount = 120 },
        [30] = { type = 'weapon', weapon = 'heavysniper' },
        [31] = { type = 'cash', amount = 1250 },
        [32] = { type = 'item', item = 'bandage', amount = 20 },
        [33] = { type = 'cash', amount = 1500 },
        [34] = { type = 'item', item = 'ammo-shotgun', amount = 100 },
        [35] = { type = 'weapon', weapon = 'pumpshotgun' },
        [36] = { type = 'cash', amount = 1750 },
        [37] = { type = 'item', item = 'medikit', amount = 6 },
        [38] = { type = 'cash', amount = 2000 },
        [39] = { type = 'item', item = 'ammo-shotgun', amount = 150 },
        [40] = { type = 'weapon', weapon = 'combatshotgun' },
        [41] = { type = 'cash', amount = 2500 },
        [42] = { type = 'item', item = 'bandage', amount = 25 },
        [43] = { type = 'cash', amount = 3000 },
        [44] = { type = 'item', item = 'ammo-9', amount = 200 },
        [45] = { type = 'weapon', weapon = 'minigun' },
        [46] = { type = 'cash', amount = 3500 },
        [47] = { type = 'item', item = 'medikit', amount = 8 },
        [48] = { type = 'cash', amount = 4000 },
        [49] = { type = 'item', item = 'ammo-rifle', amount = 300 },
        [50] = { type = 'weapon', weapon = 'remotesniper' },
    },
    xpSources = {
        zombieKill = 50,
        waveComplete = 500,
        safeZoneMinute = 5,
        dailyLogin = 100,
    }
}
